spring.application.name=taskflow

server.port=8080

app.name=TaskFlow
app.version=1.0

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=janidubomal
spring.datasource.password=bomal9978
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true