# application-prod.properties

server.port=8080
app.environment=production

#spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
#spring.datasource.username=janidubomal
#spring.datasource.password=bomal9978
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskflow}
spring.datasource.username=${DB_USERNAME:janidubomal}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#management.endpoint.health.show-details=always
#management.endpoints.web.exposure.include=health,info,metrics,loggers
#logging.level.root=INFO
#logging.level.com.example.taskflow=DEBUG
#logging.file.name=logs/taskflow.log
logging.level.com.example.taskflow=INFO
management.endpoint.health.show-details=never
